language: python
python:
  - "3.6.4"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest -v crm_solver.odetest.OdeTest
  - python -m unittest -v crm_solver.beamlettest.BeamletTest
  - python -m unittest -v crm_solver.atomic_dbtest.AtomicDBTest
